baseURL = "http://localhost:1313/EMPC_workshop/"
#baseURL = "https://pfloos.github.io/EMPC_workshop/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "EMPC WORKSHOP (Toulouse, ??-?? Apr 2027)"
[Params]
  hometitle = "Embedding in Math, Physics and Chemistry"
  logo="img/EMPC.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/EMPC.png"
  desc = "EMPC WORKSHOP"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "EMPC WORKSHOP"
   email = "cmejutozaera@irsamc.ups-tlse.fr"
   github = "pfloos"
#   twitter = "GDR_NBODY"
#   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Program"
    url = "planning"
    weight = 2

 [[menu.main]]
     name="Science"
     url = "presentations"
     weight = 3

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 4

